### ISSUE TITLE
Add FIXME supported

### ISSUE THREAD

**Issue by KevinZonda** [mrlacey/WarnAboutTodos#11]
FIXME is a very useful label as is TODO.
So how about waring FIXME?

**Comment by mrlacey** [comment]
@KevinZonda 

There are already config options that will allow you to do this.

1. Create a file called `todo-warn.config` add it to the project and set the build action to `AdditionalFiles`

![image](https://user-images.githubusercontent.com/189547/77749179-7b19c080-7019-11ea-8d7b-14160926236f.png)

> A todo-warn.config file can also be specified in your user's ApplicationData directory. (You can get to this by entering %appdata% in the File Explorer address bar.) Project-level configurations will override the user level configuration if they exist.

In that file, set the contents like this:

```
[WARN][STARTS(TODO)]
[WARN][STARTS(FIXME)]
```
![image](https://user-images.githubusercontent.com/189547/77749353-cfbd3b80-7019-11ea-8669-3e6057e792eb.png)

Ignore the red squiggles added by Visual Studio.

Any comments starting `FIXME` will then show up in the warnings. Like this:
![image](https://user-images.githubusercontent.com/189547/77749501-085d1500-701a-11ea-83ab-f028cf87f2f9.png)


You can read more about configuration options at https://github.com/mrlacey/WarnAboutTodos/blob/master/README.md#configuration

---

Does this give you everything you need?

**Comment by KevinZonda** [comment]
Fantastic! Thanks a lot!

**Comment by mrlacey** [comment]
> Fantastic! Thanks a lot!

Glad this helps. You can help me spread the word so others can find this tool too, by [leaving a review in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WarnAboutTODOs&ssr=false#review-details). :)
