### ISSUE TITLE
Suggestion: Add possibility of using token for "any number" as term

### ISSUE THREAD

**Issue by xJom** [mrlacey/WarnAboutTodos#12]
It would be nice if you could use a regular expression for the TODO-comment, e g CONTAINS(Issue #[d]+).

**Comment by mrlacey** [comment]
Thanks for the suggestion @xJom 

2 questions:

1. Is it just `CONTAINS` that you'd want/need this for, or other options as well?
2. Would it be ok to add a `CONTAINSREGEX()` option and whatever is within the brackets be treated as a regular expression?

**Comment by xJom** [comment]
1. Yes. If it is a full regex implementation you can do CONTAINSREGEX($...), so you do not need STARTSREGEX(). I think it is possible to do a negative match also, so DOESNOTCONTAINREGEX is not needed either.
2. Yes.

**Comment by mrlacey** [comment]
Implementing this with the configuration keyword `MATCHESREGEX` 

e.g. `[MATCHESREGEX(Issue #[\d]+)]`

This will cause a warning for any comment including "Issue #" followed by any number of digits

![image](https://user-images.githubusercontent.com/189547/98256770-de3be000-1f76-11eb-8908-f225059b9d4d.png)

**Comment by mrlacey** [comment]
This has now been released as version 1.6 ([NuGet](https://www.nuget.org/packages/WarnAboutTODOs/1.6.0) & [VSIX](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WarnAboutTODOs))

**Comment by xJom** [comment]
That was rather quick fixed! Thank you!

**Comment by mrlacey** [comment]
If you've found this extension helpful, please leave a rating/review at https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WarnAboutTODOs&ssr=false#review-details

Also, feel free to open any new issues with further suggestions for improvements.
