### ISSUE TITLE
Messages and warnings doesn't show up in Error List Window unless I opened the file

### ISSUE THREAD

**Issue by fraluderin** [mrlacey/WarnAboutTodos#14]
Let's suppose I have a TODO note in File1.xaml.vb.
When I open VS (2022) and I build the solution, nothing appears in error list window. If I open File1.xaml.vb, the TODO note shows up and stays there even if I close the file (this is what I expect, as I'd like to see all the notes without having to open each file).
I configured the extension with a custom TODO-Warn.config file as following: 
```
[INFO][STARTS(TODO)]
[INFO][STARTS(INFO)]
[WARN][STARTS(JC)] 
```

**Comment by mrlacey** [comment]
As you're using VS2022, I assume you have the NuGet package installed in your project.
The way analyzers (which is what the NuGet package is) work within Visual Studio is controlled by your settings.

As you're using VB.NET, go to  **Tools** > **Options** > **Text Editor** > **Basic** > **Advanced**.
Change the **Background analysis scope** to **Entire Solution**. Then try again.

![image](https://user-images.githubusercontent.com/189547/143678719-4242042c-526c-44c0-8fac-c6f0e2d9df1e.png)


I believe this should address the problem you're seeing.

**Comment by fraluderin** [comment]
I tried this. This actually solve the issue, but unfortunately fills my error list window with designer-generated info.

![image](https://user-images.githubusercontent.com/13141581/143688496-a5105341-4fee-42b4-b6cd-6eaad2cb5e12.png)

**Comment by mrlacey** [comment]
I think this is a consequence of the way analyzers work and the fact you want what is found to show up as **info**rmation. These don't show up in the build output by default and so won't make it to the error list window.

If you change the config to output everything as a Warning or Error, but with the background analysis scoped to Open Documents.

It's also possible that level of configured Output Verbosity may be affecting this too. If you set this to "Detailed" you may see more in the error list without doing solution-wide analysis in the background.

**Comment by fraluderin** [comment]
Thank you, I understood.
If in future will be a way to change this behavior, I will surely appreciate it.
I'll keep using this extension- it's one of my favorites.

**Comment by mrlacey** [comment]
> Thank you, I understood. If in future it will be possibile to change this behavior, I will surely appreciate it. I'll keep using this extension- it's one of my favorites.

Sadly, unless the way analyzers change, the only way to change the behavior of this extension would be to rewrite it in an entirely different way and that's very unlikely. sorry

**Comment by fraluderin** [comment]
No problem, the extension does its work well as it is now.
Thank you!
