### ISSUE TITLE
Look for default config in user home

### ISSUE THREAD

**Issue by kbuzby** [mrlacey/WarnAboutTodos#8]
I'm using this at work with a relatively large shared code base (many projects shared between many solutions).  

Since I am using this personally I'm running into two things:  
- I'd like to filter down TODO comments to just my own, which I can do with the config file, but...  
- I don't necessarily want to add a config file to each project, or have to worry about making sure I don't commit that file / working around that.

I think it would be a nice option for the addin to fall back to a user default config, likely in the user home directory. I think it would amount to doing an additional file search after this line in the user home, if it was not set by the project level already:
https://github.com/mrlacey/WarnAboutTodos/blob/1590d8503266b44901684b2193cbb384a764fe48/src/WarnAboutTODOs/WarnAboutTODOsAnalyzer.cs#L77

I'd be more than happy to contribute as a PR, if you're open to that!

**Comment by mrlacey** [comment]
I'm open to a PR.
Need to think carefully about where the file should go. My initial thought is under `SpecialFolders.ApplicationData`

**Comment by kbuzby** [comment]
That makes sense to me as well, but seems like there might be a catch.   
Taking a quick look at it, [`Environment.GetFolderPath`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netstandard-2.0) and the `Environment.SpecialFolder` enum are only available in .NET Standard 2.0 and this project is on 1.3.
Are you ok with an update to that as well?

**Comment by mrlacey** [comment]
> That makes sense to me as well, but seems like there might be a catch.
> Taking a quick look at it, [`Environment.GetFolderPath`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath?view=netstandard-2.0) and the `Environment.SpecialFolder` enum are only available in .NET Standard 2.0 and this project is on 1.3.
> Are you ok with an update to that as well?

Happy to update if it still works on VS2017 & 2019.

Current targeting is only based on the project template default.

**Comment by mrlacey** [comment]
This functionality is in [version 1.5 which is available now](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WarnAboutTODOs).
